CREATE TABLE EMPLOYMENT_LOGS
(
    employment_log_id              NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    first_name                     VARCHAR(255) NOT NULL,
    last_name                      VARCHAR(255) NOT NULL,
    employment_action              VARCHAR(5)   NOT NULL,
    employment_status_updtd_tmstmp TIMESTAMP,
    CONSTRAINT employment_action_check CHECK (employment_action = 'HIRED' OR employment_action = 'FIRED')
);

CREATE
OR REPLACE PROCEDURE INSERT_LOG(first_name EMPLOYMENT_LOGS.first_name% type,
                                    last_name EMPLOYMENT_LOGS.last_name% type,
                                    employment_action EMPLOYMENT_LOGS.employment_action% type)
    IS
BEGIN
INSERT INTO EMPLOYMENT_LOGS(first_name, last_name, employment_action, employment_status_updtd_tmstmp)
VALUES (first_name, last_name, employment_action, CURRENT_TIMESTAMP);
END;